# Generated by Django 6.0.1 on 2026-01-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojavida', '0011_alter_datospersonales_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
